apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1 # Number of pod replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: python:3.11 # Base Python image
          command: ["python"]
          args: ["app.py"]
          ports:
            - containerPort: 5000 # Flask's default port
          env:
            - name: FLASK_ENV
              value: "production"
          volumeMounts:
            - name: app-source
              mountPath: /app
      volumes:
        - name: app-source
          configMap:
            name: flask-app-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # Expose the service on port 80
      targetPort: 5000 # Target Flask port in the container
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flask-app-route
spec:
  to:
    kind: Service
    name: flask-app-service
  port:
    targetPort: 5000 # The same as container's port
  tls:
    termination: edge # Set this if you want HTTPS termination at the edge
